[package]
name = "l19_terminal_tictactoe"
version = "0.1.1"
edition = "2021"
description = "A game of Tic Tac Toe played on the command line; Educational exercise."
license = "MIT OR Apache-2.0"

[dependencies]
rand = "^0.8.5" #Random number generator.
